apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/kuber/*
build:
  local:
    push: false
  artifacts:
    - image: nycgio/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: nycgio/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: nycgio/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: nycgio/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: nycgio/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: nycgio/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
